var Bingo_Value_Comments = {
	1:"Agora começou o jogo",
	2:"Só um patinho na lagoa",
	3:"Uma pequena muôsca",
	4:"Pernas da mesa",
	5:"Áu áu, olha o cachorro",
	6:"Meia dúzia!",
	7:"Um machado",
	8:"Biscoito",
	9:"Pingo no pé nove é",
	10:"O craque de bola",
	11:"Dois gaúchos: um atrás do outro",
	12:"Um dúzia",
	13:"Número da sorte do Zagalo",
	14:"Dia de São Valentim",
	15:"Debutante",
	16:"O leão tá solto",
	17:"Este ano",
	18:"Virou adulto",
	19:"Cadê o pavão",
	20:"Perú de Natal",
	21:"Olha o touro",
	22:"Dois patinhos na lagoa",
	23:"Um pato e uma muôsca",
	24:"Rapazinho alegre, ai como dói",
	25:"Um pato e um mergulho",
	26:"Holandês",
	27:"Pequeno pato com muleta",
	28:"Vem torto que eu endireito",
	29:"O famoso São Pedro",
	30:"Não minta, saiu trinta",
	31:"Final de mês grande",
	32:"O revolvinho",
	33:"Idade de Cristo",
	34:"Tripa de mocotó e fato",
	35:"Triste Chico",
	36:"Três duzias",
	37:"Uma muôsca no paraíso",
	38:"Justiça de Goiás",
	39:"Trinta e tudo",
	40:"A idade da loba",
	41:"A vida começou",
	42:"Aquela rua famosa em Nova York",
	43:"Pocotó, pocotó, lá vem o cavalo",
	44:"Cuará cuaa cuaa",
	45:"Fim do primeiro tempo",
	46:"Mais truques",
	47:"Quatro e sete",
	48:"O sanfonão",
	49:"Quarenta e tudo",
	50:"É penta",
	51:"Uma boa ideia",
	52:"Cartas do baralho",
	53:"Preso numa árvore",
	54:"Limpa o chão",
	55:"Dois cachorros do padre",
	56:"Ela valia a pena?",
	57:"Do ladrão",
	58:"Primeira copa",
	59:"Cinquenta e tudo",
	60:"Para descansar cê senta",
	61:"Pão de forma do padeiro",
	62:"Segunda copa",
	63:"Faz-me cócegas",
	64:"Número dos Beatles",
	65:"Hora de parar de trabalhar",
	66:"Um tapa atrás da oreia, meia meia",
	67:"Me acerte, sessenta e sete",
	68:"Sargento biscoito",
	69:"Virando cambota, um pra cima e outro para baixo",
	70:"Até conseguir cê tenta",
	71:"Dona Clotilde é a bruxa do",
	72:"Se Madruga",
	73:"Uma bengala de uma muôsca",
	74:"Tá acabando o jogo",
	75:"Terminou o jogo",
	76:"",
	77:"Duas machadinhas",
	78:"",
	79:"",
	80:"",
	81:"",
	82:"",
	83:"",
	84:"",
	85:"",
	86:"",
	87:"",
	88:"Dois gordo",
	89:"",
	90:"A velha",
	91:"",
	92:"",
	93:"",
	94:"",
	95:"",
	96:"",
	97:"",
	98:"",
	99:""
};

var Bingo_General_Comments = [
	"",
];
